# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Location' do
  use_frameworks!

  project 'Location.xcodeproj'
  platform :ios, '14.0'

  pod 'CocoaMQTT'
  pod 'OpenSSL-Universal'
  pod 'CocoaMQTT/WebSockets', '1.3.0-rc.1'

end
